# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotionCli < Formula
  desc "Full-featured CLI for Notion. Like gh for GitHub, but for Notion."
  homepage "https://github.com/4ier/notion-cli"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/4ier/notion-cli/releases/download/v0.3.2/notion-cli_0.3.2_darwin_amd64.tar.gz"
      sha256 "7e4ca369bb87b6a2a101e4f755ace5dc9ad1ba1678ef773ac90cd63137495a8f"

      define_method(:install) do
        bin.install "notion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/4ier/notion-cli/releases/download/v0.3.2/notion-cli_0.3.2_darwin_arm64.tar.gz"
      sha256 "a6846a5698602ea979b1fdfe24ec90f00dfabae20f4f151d178985530392f8ac"

      define_method(:install) do
        bin.install "notion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/4ier/notion-cli/releases/download/v0.3.2/notion-cli_0.3.2_linux_amd64.tar.gz"
      sha256 "1c486f6e048420344dc2a04a28982df4022ca6132283d580349cf9a07b837de3"
      define_method(:install) do
        bin.install "notion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/4ier/notion-cli/releases/download/v0.3.2/notion-cli_0.3.2_linux_arm64.tar.gz"
      sha256 "ba739a8116828111954c0707a747719630681c7b4e18cd6da191dfb74be325e9"
      define_method(:install) do
        bin.install "notion"
      end
    end
  end
end
